FROM mcr.microsoft.com/azureml/onnxruntime:v0.5.0-tensorrt-l4t-r32.2
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update && \
    apt-get install libssl-dev libffi-dev --yes

RUN pip3 install --upgrade pip

COPY rotnet_street_view_mobilenet_v2.onnx ./

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY test.png ./
COPY main.py ./

CMD [ "python3", "-u", "./main.py" ]